version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven || apt-get install -y maven
      - mvn --version

  pre_build:
    commands:
      - echo Resolving dependencies...
      - mvn install -DskipTests

  build:
    commands:
      - echo Building the project...
      - mvn clean package

  post_build:
    commands:
      - echo Running post-build actions...

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
