version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Resolving dependencies...
      - sudo apt install maven -y

  build:
    commands:
      - echo Building the project...
      - mvn clean package

  post_build:
    commands:
      - echo Running post-build actions...

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - ~/.m2/**/*
