version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using pre-installed Maven..."
      - mvn --version

  pre_build:
    commands:
      - echo Resolving dependencies...
      - mvn install -DskipTests

  build:
    commands:
      - echo Building the project...
      - mvn clean package

  post_build:
    commands:
      - aws lambda update-function-code --function-name ColumbusEventsFunction --zip-file fileb://target/demo-0.0.1-SNAPSHOT.jar
 - echo Uploading package to S3...
      - aws s3 cp demo-0.0.1-SNAPSHOT.jar s3://columbuseventss3/demo-0.0.1-SNAPSHOT.jar
      - echo Updating Lambda function...
      - aws lambda update-function-code --function-name <your-lambda-function-name> --s3-bucket columbuseventss3 --s3-key demo-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - ~/.m2/**/*
